version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
    # volumes:
    #   - .:/app
    networks:
      - nestjs-network
    restart: unless-stopped

networks:
  nestjs-network:
    driver: bridge
