version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "81:8080"
    environment:
      NODE_ENV: production
    # volumes:
    #   - .:/app
    networks:
      - nestjs-network
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - nestjs-network
    restart: unless-stopped

networks:
  nestjs-network:
    driver: bridge
